services:
  producer:
    build: .
    container_name: producer
    restart: always
    env_file:
      - .env
    volumes:
      - producer_data:/var/lib/producer
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - rabbitmq_rabbitmq_network
      - api_erp_mynetwork

volumes:
  producer_data:

networks:
  rabbitmq_rabbitmq_network:
    external: true
  api_erp_mynetwork:
    external: true
